# -*- coding: utf-8 -*-
"""FaceRec_GUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161qDTvXtbsxSod2WIIXgLczJBSDCXIQI
"""

import streamlit as st

st.set_page_config(page_title="Test App", layout="wide")

st.write("If you see this, it's working 🎉")